# Generated by Django 3.1.5 on 2021-02-03 13:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("comments", "0002_comment_owner"),
        ("tickets", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="ticket",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="tickets.ticket",
            ),
        ),
        migrations.AddField(
            model_name="comment",
            name="user_owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="posted_comments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
