<<<<<<< HEAD
# Generated by Django 3.1.5 on 2021-02-03 13:59
=======
# Generated by Django 3.1.5 on 2021-02-03 12:39
>>>>>>> development

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
<<<<<<< HEAD
=======
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
>>>>>>> development
        ('group_members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('types', models.CharField(choices=[('Bug', 'Bug'), ('New Feature', 'New Feature'), ('Update Feature', 'Update Feature'), ('Delete Feature', 'Delete Feature')], default='Bug', max_length=14)),
                ('description', models.TextField(max_length=300)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(blank=True, choices=[('New', 'New'), ('In Progress', 'In Progress'), ('FeedBack', 'Feedback'), ('Blocked', 'Blocked'), ('Resolved', 'Resolved')], default='New', max_length=15)),
                ('assigned_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='tickets', to='group_members.groupmember')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_tickets', to='group_members.groupmember')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='projects.project')),
                ('user_owner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_tickets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
