# Generated by Django 3.1.5 on 2021-01-28 18:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('types', models.CharField(choices=[('BG', 'Bug'), ('NF', 'New Feature'), ('UF', 'Update Feature'), ('DF', 'Delete Feature')], default='BG', max_length=2)),
                ('description', models.TextField(max_length=300)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(blank=True, choices=[('New', 'New'), ('In Progress', 'In Progress'), ('FeedBack', 'Feedback'), ('Blocked', 'Blocked'), ('Resolved', 'Resolved')], default='New', max_length=15)),
                ('owner', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_ticket', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='projects.project')),
            ],
        ),
    ]
