# Generated by Django 3.1.5 on 2021-01-28 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='types',
            field=models.CharField(choices=[('Bug', 'Bug'), ('New Feature', 'New Feature'), ('Update Feature', 'Update Feature'), ('Delete Feature', 'Delete Feature')], default='Bug', max_length=14),
        ),
    ]
