# Generated by Django 3.1.5 on 2021-01-28 11:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='number',
        ),
        migrations.AddField(
            model_name='ticket',
            name='status',
            field=models.CharField(blank=True, choices=[('NW', 'New'), ('IP', 'In Progress'), ('DF', 'Blocked'), ('FB', 'Feedback'), ('RV', 'Resolved')], default='NW', max_length=2),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='owner',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_ticket', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='types',
            field=models.CharField(choices=[('BG', 'Bug'), ('NF', 'New Feature'), ('UF', 'Update Feature'), ('DF', 'Delete Feature')], default='BG', max_length=2),
        ),
    ]
