# Generated by Django 3.1.5 on 2021-01-28 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_auto_20210128_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(blank=True, choices=[('New', 'New'), ('In Progress', 'In Progress'), ('DF', 'Blocked'), ('FB', 'Feedback'), ('RV', 'Resolved')], default='New', max_length=15),
        ),
    ]
