# Generated by Django 3.1.5 on 2021-01-28 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_auto_20210128_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(blank=True, choices=[('New', 'New'), ('In Progress', 'In Progress'), ('FeedBack', 'Feedback'), ('Blocked', 'Blocked'), ('Resolved', 'Resolved')], default='New', max_length=15),
        ),
    ]
