# Generated by Django 3.1.5 on 2021-01-28 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmember',
            name='role',
            field=models.CharField(choices=[('manager', 'Manager'), ('developer', 'Developer')], default='developer', max_length=15),
        ),
    ]
