# Generated by Django 3.1.5 on 2021-01-28 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20210128_0957'),
        ('group_members', '0002_auto_20210128_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmember',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='projects.project'),
        ),
    ]
