# Generated by Django 3.1.5 on 2021-01-28 14:54

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20210128_0957'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('group_members', '0003_auto_20210128_1327'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='groupmember',
            unique_together={('user', 'project')},
        ),
    ]
